spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  config:
    import: dev.yml

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3h
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: springnogito
        provider:
          cognito:
            issuer-uri: ${issuer-url}
            user-name-attribute: username
aws:
  cognito:
    logoutUrl: ${logoutUrl}
    logout:
      success:
        redirectUrl: ${logout-redirect-url}

javamelody:
  enabled: true